### ISSUE TITLE
[1.14.4] Crash when installing on server

### ISSUE THREAD

**Issue by KajesLorian** [RomoAlamN/CauldronBrewing#5]
Minecraft 1.14.4
Forge 28.2.0
CualdronBrewing Cauldron-1.14-1.1

Installed on client, worked fine.

Installed on server, crashed.

https://pastebin.com/rGVCupuW

**Comment by RomoAlamN** [comment]
Sorry about that, It was fixed in 1.15, but I hadn't updated the 1.14 release to match

**Comment by RomoAlamN** [comment]
I'll upload the new version soon

**Comment by RomoAlamN** [comment]
Fixed in next release
